# Generated by Django 3.0 on 2019-12-31 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_auto_20191231_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
