# Generated by Django 3.0 on 2019-12-31 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_auto_20191231_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='website',
            field=models.URLField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
