# Generated by Django 3.0 on 2019-12-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_auto_20191231_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
